### ISSUE TITLE
Azure pipeline not get last changed

### ISSUE THREAD

**Issue by Tomelin** [mohamedelhabib/vsts-changed-files-multibranch#3]
Hi,

I'm using the task to validate what's the files changed on last commit but it is return all files changed.

we are using this format:
```
jobs:
    - job: CheckFilesCommand
      dependsOn: []
      displayName: Check changed files
      steps: 
        - task: ChangedFiles@1
          name: CheckFilesChanged
          inputs:
            refBranch: develop
            rules: src/functionPath/**
            variable: HasChanged
```

the tests return this files
```
/usr/bin/git log -m -1 --name-only --pretty=format: da5bae0ab16b5c4bc51ee863c2a9020b02a5589f
src/FunctionName01/dependencies-pipeline/dependencies-azure-pipeline.yml
/usr/bin/git log -m -1 --name-only --pretty=format: 95f4cc5d9aa76f78eac6ab77dad42c76f3ed6d6d
.azuredevops/azure-pipelines.yml
/usr/bin/git log -m -1 --name-only --pretty=format: 69fe073bc532ffd1d4d33df3a299ff124c871558
src/FunctionName01/dependencies-pipeline/dependencies-azure-pipeline.yml
/usr/bin/git log -m -1 --name-only --pretty=format: 3380c8324801b2931eed662ff3209c3a86d9adc8
src/FunctionName01/dependencies-pipeline/dependencies-azure-pipeline.yml
/usr/bin/git log -m -1 --name-only --pretty=format: 3bbf0e79eb637ab0253993d5b17311006154dbf1
src/FunctionName01/dependencies-pipeline/helm-develop.yml
/usr/bin/git log -m -1 --name-only --pretty=format: 16a93acc2a65ec3d492e5b24cff72a38e0fefd9a
src/FunctionName01/dependencies-pipeline/helm-develop.yml
/usr/bin/git log -m -1 --name-only --pretty=format: d2b09194ad187dfff936a24c0f7f7af39079c2a8
src/FunctionName01/dependencies-pipeline/helm-develop.yml
/usr/bin/git log -m -1 --name-only --pretty=format: 063456a19980dae7eed8e1a35adc4e224d1604e5
src/BrandJob/dependencies-pipeline/helm-develop.yml
/usr/bin/git log -m -1 --name-only --pretty=format: bbe39cd9a6dd9110b06a780cb5a657a6044542cd
src/FunctionName02/dependencies-pipeline/helm-develop.yml
src/FunctionName03/dependencies-pipeline/helm-develop.yml
src/FunctionName04/dependencies-pipeline/helm-develop.yml
src/FunctionName05/dependencies-pipeline/helm-develop.yml
/usr/bin/git log -m -1 --name-only --pretty=format: 5421926990be6f129bd53fc814ebd2f9177bb82c
src/FunctionName06/dependencies-pipeline/helm-develop.yml

/usr/bin/git log -m -1 --name-only --pretty=format: a18698828c82384529b2b1225bc0c89505640fe6
src/FunctionName01/teste
```

But I only changed ```src/FunctionName01/dependencies-pipeline/dependencies-azure-pipeline.yml```file.

1. What's the options on variable parameter?
2. how to do recognize files only from the last commit?
