### ISSUE TITLE
fatal: ambiguous argument 'main...': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by doggy8088** [mohamedelhabib/vsts-changed-files-multibranch#8]
I always get the following error. Can you help me identify what's the root cause?

```log
Starting: Check changed files: READMEHasChanged
==============================================================================
Task         : Check Changed Files Multibranch
Description  : Pipeline task to check if some files changed since last build and support multibranch
Version      : 2.5.0
Author       : MohamedElhabib
Help         : https://marketplace.visualstudio.com/items?itemName=mohamedelhabib.vsts-changed-files-multibranch
==============================================================================
get the list of changes for the build 14017
Build id is 14017
refBranch = main
currentBranch = refs/pull/23/merge
compare refs/pull/23/merge with the ref branch main...
C:\agents\3.234.0\externals\git\cmd\git.exe diff --name-only main...
fatal: ambiguous argument 'main...': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Changed files are : 
>> READMEHASCHANGED: No change detected since last succeeded build, setting "READMEHasChanged" to "false"
Finishing: Check changed files: READMEHasChanged
```

Here is my YAML for this task:

```yaml
steps:
- task: MohamedElhabib.vsts-changed-files-multibranch.vsts-changed-files-multibranch.ChangedFilesMultibranch@2
  displayName: 'Check changed files: READMEHasChanged'
  inputs:
    rules: README.md
    variable: READMEHasChanged
    refBranch: main
    forceToTrue: false
    verbose: true
```

I do have a `main` branch.
